# Generated by Django 3.2.3 on 2021-06-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcrip',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('city', models.CharField(default='Desconocido', max_length=100)),
                ('country', models.CharField(default='Desconocido', max_length=100)),
            ],
        ),
    ]
