# Generated by Django 3.2.3 on 2021-06-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcrip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcrip',
            name='audio',
            field=models.FileField(default=1, upload_to='audio_files'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcrip',
            name='descrip',
            field=models.FileField(default=1, upload_to='pdf_files'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcrip',
            name='transcrip',
            field=models.FileField(default=1, upload_to='pdf_files'),
            preserve_default=False,
        ),
    ]
